jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: "admin"
        name: "admin"
        password: "changeme"
credentials:
  system:
    domainCredentials:
      - credentials:
        - azure:
            id: Azure-TestChallenge-SP
            scope: GLOBAL
            azureEnvironmentName: "Azure"
            subscriptionId: ${AZ_SP_SUBSCRIPTION_ID}
            clientId: ${AZ_SP_CLIENT_ID}
            clientSecret: ${AZ_SP_CLIENT_SECRET}
            tenant: ${AZ_SP_TENANT_ID}
security:
  scriptApproval:
    approvedSignatures:
      - "staticField com.cloudbees.plugins.credentials.CredentialsScope GLOBAL"
      - "new com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl com.cloudbees.plugins.credentials.CredentialsScope java.lang.String java.lang.String java.lang.String java.lang.String"
      - "staticMethod com.cloudbees.plugins.credentials.SystemCredentialsProvider getInstance"
      - "method com.cloudbees.plugins.credentials.SystemCredentialsProvider getStore"
      - "staticMethod com.cloudbees.plugins.credentials.domains.Domain global"
      - "method com.cloudbees.plugins.credentials.CredentialsStore addCredentials com.cloudbees.plugins.credentials.domains.Domain com.cloudbees.plugins.credentials.Credentials"
groovy:
  - script: >
      import com.cloudbees.plugins.credentials.*;
      import com.cloudbees.plugins.credentials.common.*;
      import com.cloudbees.plugins.credentials.domains.*;
      import com.cloudbees.plugins.credentials.impl.*;
      import org.jenkinsci.plugins.docker.commons.credentials.*;
      import jenkins.model.*
      
      domain = Domain.global();
      parent = Jenkins.instance;
      store = parent.getExtensionList('com.cloudbees.plugins.credentials.SystemCredentialsProvider')[0].getStore();
      
      // Adds the DinD certificates to Jenkins to allow authentication
      
      dockerCertCred = new DockerServerCredentials(
        CredentialsScope.GLOBAL,
        "Docker-Certificate-Integration",
        "",
        new File('/machines/docker/key.pem').text,
        new File('/machines/docker/cert.pem').text,
        new File('/machines/docker/ca.pem').text
      );

      store.addCredentials(domain, dockerCertCred);
jobs:
  - script: >
        multibranchPipelineJob('testchallenge-build') {
          branchSources {
            branchSource {
              source {
                git {
                  id('testchallenge-build-branches')
                  remote('https://github.com/ncostello81/TechChallengeApp.git')
                  traits {
                    gitBranchDiscovery()
                  }
                }
              }
              strategy {
                allBranchesSame {
                  props {
                    suppressAutomaticTriggering()
                  }
                }
              }
            }
          }
          factory {
            workflowBranchProjectFactory {
              scriptPath('Jenkinsfile')
            }
          }
        } 
  - script: >
        pipelineJob('testchallenge-deploy') {
          parameters {
            imageTag {
              name('TAG')
              description('Select the tag you would like to deploy...')
              image('techchallengeapp')
              filter('.*')
              registry('https://acrsrvntestnc81.azurecr.io')
              credentialId('Container-Registry-Creds')
              tagOrder('NATURAL')
            }
          }
          definition {
            cpsScm {
              scriptPath('./deploy/Jenkinsfile')
              scm {
                git {
                  remote {
                    url('https://github.com/ncostello81/TechChallengeApp.git')
                  }
                  branch('*/initial-deploy-pipe')
                  extensions {}
                }
              }
            }
          }
        }
  - script: >
        multibranchPipelineJob('testchallenge-platform') {
          branchSources {
            branchSource {
              source {
                git {
                  id('testchallenge-platform-branches')
                  remote('https://github.com/ncostello81/TechChallengeApp.git')
                  traits {
                    gitBranchDiscovery()
                  }
                }
              }
              strategy {
                allBranchesSame {
                  props {
                    suppressAutomaticTriggering()
                  }
                }
              }
            }
          }
          factory {
            workflowBranchProjectFactory {
              scriptPath('platform/Jenkinsfile')
            }
          }
        } 